### PR TITLE
Changing order of expression for L in LU Decomp

### PR DESCRIPTION
**Pull request by lukemmtravis**

### CODE REVIEW

**Comment by TSGut** [comment]
Happy with these to be merged?

**Comment by dlfivefifty** [comment]
Can you fix the Decompositions.jmd file?

**Comment by TSGut** [comment]
Ah, these are the Jupyter notebooks only. @lukemmtravis The changes should also be made in the Decompositions.jmd file like Sheehan said.

**Comment by lukemmtravis** [comment]
Sure, just did that now.

Best

Luke

**Pull request merged**
