### PR TITLE
Altering solution of Prob 5.1.

### PR DESCRIPTION
**Pull request by lukemmtravis**

### CODE REVIEW

**Comment by TSGut** [comment]
I agree that the stated intervals are incorrect but I think your change is still incorrect. Your second change is correct but the first case with all negative should read [bd,ac].

Just for the sake of completion:

Consider the case a,b,c,d < 0 for intervals [a,b] and [c,d]. For intuition and counterexample consider the example [a,b]=[-4,-2] and [c,d]=[-3,-1]. AB is then [2,12] which as said is [bd,ac].

Next let's think about a,b<0 and c,d>0. Consider [a,b] = [-4,-2] and [c,d] = [1,3]. Then AB is [-12,-2], which is [ad,bc] as currently correctly stated in the repo.

Next is a,b>0 and c,d<0. By commutativity this is equivalent to the previous case with swapped out endpoints, so it's easy to see that this should be [bc,ad], again the repo version is correct there.

The last one a,b,c,d > 0 is also clearly incorrect in the current repo version. Consider the example [a,b]=[2,4] and [c,d]=[1,3]. Then AB is [2,12] which is [ac,bd], so your proposed change is correct and the repo version is wrong.

**Comment by TSGut** [comment]
Looks good to me now. 👍

**Comment by lukemmtravis** [comment]
Thanks for spotting the mistake!

**Comment by dlfivefifty** [comment]
Thanks!

**Pull request merged**
