### PR TITLE
Fix problem sheet numbering (5.4 -> 5.3)

### PR DESCRIPTION
**Pull request by TSGut**
Seems we skipped a number there, this just fixes the numbering to avoid confusion.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Please make the change in the .jmd files

**Comment by TSGut** [comment]
Right, forgot that these are generated with Weave. Should be fixed now.

**Comment by dlfivefifty** [comment]
Also week1s.jmd (I haven’t figured out how to avoid repetition)

**Comment by TSGut** [comment]
done

**Pull request merged**
